//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gato.ServicioGato {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:TikTakToe", ConfigurationName="ServicioGato.TikTakToePort")]
    public interface TikTakToePort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TikTakToe#TikTakToe#turno", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string turno(int coordenadaX, int coordenadaY, string caracter);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TikTakToe#TikTakToe#turno", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> turnoAsync(int coordenadaX, int coordenadaY, string caracter);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TikTakToe#TikTakToe#revisarGanador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool revisarGanador();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TikTakToe#TikTakToe#revisarGanador", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> revisarGanadorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TikTakToe#TikTakToe#obtenerRecords", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string obtenerRecords();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:TikTakToe#TikTakToe#obtenerRecords", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> obtenerRecordsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TikTakToePortChannel : Gato.ServicioGato.TikTakToePort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TikTakToePortClient : System.ServiceModel.ClientBase<Gato.ServicioGato.TikTakToePort>, Gato.ServicioGato.TikTakToePort {
        
        public TikTakToePortClient() {
        }
        
        public TikTakToePortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TikTakToePortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TikTakToePortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TikTakToePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string turno(int coordenadaX, int coordenadaY, string caracter) {
            return base.Channel.turno(coordenadaX, coordenadaY, caracter);
        }
        
        public System.Threading.Tasks.Task<string> turnoAsync(int coordenadaX, int coordenadaY, string caracter) {
            return base.Channel.turnoAsync(coordenadaX, coordenadaY, caracter);
        }
        
        public bool revisarGanador() {
            return base.Channel.revisarGanador();
        }
        
        public System.Threading.Tasks.Task<bool> revisarGanadorAsync() {
            return base.Channel.revisarGanadorAsync();
        }
        
        public string obtenerRecords() {
            return base.Channel.obtenerRecords();
        }
        
        public System.Threading.Tasks.Task<string> obtenerRecordsAsync() {
            return base.Channel.obtenerRecordsAsync();
        }
    }
}
